### ISSUE TITLE
Share feature

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#18]
- [x] create share pop up modal after we find out what it should look like
- [x] user can share site via facebook (on desktop and mobile) 
- [x] user can share site via twitter (on desktop and mobile)
- [x] user can share cartoonified image via facebook (on desktop and mobile) 
- [x] user can share cartoonified image via twitter (on desktop and mobile)

From developer brief: 

> If “Share” is clicked, then there appears 2 ways of sharing the image: Twitter and Facebook. These are the optimum ways of sharing the image:
> 
> Facebook: a link to the Eu Compliant meme generator with the resulting image from this upload as the metadata
> Twitter: sharing the image with the social copy - “No need to save your memes. Just make them Certified EU Compliant™! #SaveYourInternet [insert URL]”
>

**Comment by lucymk** [comment]
@aaronparr share copy for the links that share just the site would be great 😃 and if you want any hashtags or attribution to twitter users, as outlined here: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview.html

**Comment by aaronparr** [comment]
Quick Q just to confirm: would this be to share the site with the metadata image being the user's generated meme? If not, what would it look like on both platforms?

**Comment by lucymk** [comment]
Hey @aaronparr - sorry just saw this. I meant the sharing of the site without the image, which I think is what is supposed to happen when you click either of the icons in the top right of the screen, these ones:
![screen shot 2019-01-04 at 17 10 39](https://user-images.githubusercontent.com/13594621/50700891-b3636680-1043-11e9-9f11-6b236b4f5978.png)

We can chat more about sharing on Monday though, having spent the day working on this it is seeming like the exact functionality you're looking for might not be possible due to the way Facebook and Twitter get data from pages. I'm researching it further though to see if I can find a solution 😃

**Comment by aaronparr** [comment]
Morning Lucy! Sorry, that makes sense. Do you mean the title and description of the link, as well as the text? I haven't seen a site where it autofills the text for a facebook share but I've put some copy below in case you've found a way around:

Headline: Make ANY Meme EU Complaint!
Description: Try the EU Compliant Meme Generator for yourself

Twitter share: Make any meme last beyond Article 13 with the EU Compliant Meme Generator 🤖 #SaveYourInternet @createrefresh

Facebook share: Make any meme last beyond Article 13 with the EU Compliant Meme Generator 🤖

Also, we're working on a general metadata image to be used. Totally understand about sharing generated images. But it will be essential to be able to share a generated image to Facebook/Twitter, and hopefully that should be workable.

**Comment by lucymk** [comment]
@aaronparr hey there, do you have this general metadata image? 😃

**Comment by aaronparr** [comment]
![metadata-final-05](https://user-images.githubusercontent.com/44616991/51125305-3e98e500-1818-11e9-9022-c3fa867b8e0d.png)
