### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/create-refresh#32]
- [x] deploy frontend via heroku
- [x] deploy backend via AWS Elastic Beanstalk (get AWS details from Purpose)
- [x] point new domain to heroku site

**Comment by lucymk** [comment]
@aaronparr whenever you have registered the domain let me know! also, [this](https://www.netlify.com/) is what we'll be using to deploy the front end site, if you can make an account there and then let me know the email you've signed up with, I should be able to add you to the app and ultimately transfer the site to you.

**Comment by aaronparr** [comment]
We've bought the domain: compliantmemegenerator.eu Let me know what you need in order to access it.

I've signed up to netlify using the same email address via Github - Aaron.parr@purpose.com

Thank you!
